### PR TITLE
loggly: Add header support for tags

### PR DESCRIPTION
**Pull request by robert-schmidtke**
hi there,

while I was using your loggly extension for logback I noticed it was impossible to send tags along with the request so I quickly added the feature. I'm already using it and it works fine for me. thanks for the great work.

best
robert

### CODE REVIEW

**Comment by tony19** [comment]
Thanks for the contribution @robert-schmidtke. As you pointed out, it's indeed possible to tag events by configuring the [endpoint URL](https://github.com/qos-ch/logback-extensions/wiki/Loggly#configuration-settings) in the form of:

```
http://logs-01.loggly.com/inputs/<API_KEY>/tag/<TAGS_CSV>
```

For example, this XML configures logback to send log events, tagged with "foo" and "bar", to Loggly:
```xml
<configuration>
  <appender name="loggly" class="ch.qos.logback.ext.loggly.LogglyAppender">
    <endpointUrl>http://logs-01.loggly.com/inputs/inputs/${logback.loggly.inputKey}/tag/foo,bar/</endpointUrl>
    <pattern>%d{yyyy/MM/dd HH:mm:ss,SSS} [${HOSTNAME}] [%thread] %-5level %logger{36} - %m %throwable{5}%n</pattern>
  </appender>
  <root level="INFO">
    <appender-ref ref="loggly"/>
  </root>
</configuration>
```

Since the API is already flexible enough to provide tag support, I don't think this change is truly needed, but I'm open. I admit it would make the extension's API a bit easier to use in that it abstracts Loggly's API for tagging events. Are there other compelling reasons why we would want to incorporate this change?

**Comment by robert-schmidtke** [comment]
Hi,
thanks for coming back to me. I cannot quite recall how I used it to be honest. Unless it provides runtime setting of tags I believe there is no need to incorporate this addition. Thanks and best,
Robert

**Comment by jwhitehorn** [comment]
I found this issue while researching if it was possible to add tags at runtime. I do not currently see a way to do this. Am I missing something?

**Comment by tony19** [comment]
@jwhitehorn, take a look at the example above. It specify the tags "foo" and "bar" in the `<endpointUrl>`.

**Comment by tony19** [comment]
Or maybe you're looking for a way to do it dynamically/programmatically, in which case this pull request would come in handy.

**Comment by jwhitehorn** [comment]
@tony19, the later - I'm very much interested about programmatically changing the tags at runtime. 

It just looked like this PR was closed and not merged, and I wanted to voice my support for such a feature.

**Pull request closed without merging**
